#!/bin/sh

SCRIPTPATH="$(
	cd "$(dirname "$0")" || exit
	pwd -P
)"
. "$SCRIPTPATH/../lib/gitcheck"

# Get the current branch name
current_branch=$(git branch --show-current)

# Check if the local branch is behind the remote branch
if [ "$(git rev-parse HEAD)" != "$(git rev-parse '@{u}')" ]; then
	# Pull changes from the remote branch
	git pull origin "$current_branch"
else
	echo "Already up to date."
fi
